/*
 * generated by Xtext 2.16.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DialogflowConfigStandaloneSetup extends DialogflowConfigStandaloneSetupGenerated {

	def static void doSetup() {
		new DialogflowConfigStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
