/*
 * generated by Xtext 2.16.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.DialogflowConfig.ui.internal.DialogflowConfigActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DialogflowConfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DialogflowConfigActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DialogflowConfigActivator activator = DialogflowConfigActivator.getInstance();
		return activator != null ? activator.getInjector(DialogflowConfigActivator.ORG_XTEXT_DIALOGFLOWCONFIG) : null;
	}

}
