/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Word</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getAbstractWord()
 * @model
 * @generated
 */
public interface AbstractWord extends EObject
{
} // AbstractWord
