/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isDynamic <em>Dynamic</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isBuiltIn <em>Built In</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#getValues <em>Values</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isIsOverridable <em>Is Overridable</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isIsEnum <em>Is Enum</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isAutomatedExpansion <em>Automated Expansion</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.EntityType#isAllowFuzzyExtraction <em>Allow Fuzzy Extraction</em>}</li>
 * </ul>
 *
 * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType()
 * @model
 * @generated
 */
public interface EntityType extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Dynamic</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dynamic</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dynamic</em>' attribute.
   * @see #setDynamic(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_Dynamic()
   * @model
   * @generated
   */
  boolean isDynamic();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isDynamic <em>Dynamic</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dynamic</em>' attribute.
   * @see #isDynamic()
   * @generated
   */
  void setDynamic(boolean value);

  /**
   * Returns the value of the '<em><b>Built In</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Built In</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Built In</em>' attribute.
   * @see #setBuiltIn(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_BuiltIn()
   * @model
   * @generated
   */
  boolean isBuiltIn();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isBuiltIn <em>Built In</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Built In</em>' attribute.
   * @see #isBuiltIn()
   * @generated
   */
  void setBuiltIn(boolean value);

  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.Entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Values</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_Values()
   * @model containment="true"
   * @generated
   */
  EList<Entity> getValues();

  /**
   * Returns the value of the '<em><b>Is Overridable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Overridable</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Overridable</em>' attribute.
   * @see #setIsOverridable(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_IsOverridable()
   * @model
   * @generated
   */
  boolean isIsOverridable();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isIsOverridable <em>Is Overridable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Overridable</em>' attribute.
   * @see #isIsOverridable()
   * @generated
   */
  void setIsOverridable(boolean value);

  /**
   * Returns the value of the '<em><b>Is Enum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Enum</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Enum</em>' attribute.
   * @see #setIsEnum(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_IsEnum()
   * @model
   * @generated
   */
  boolean isIsEnum();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isIsEnum <em>Is Enum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Enum</em>' attribute.
   * @see #isIsEnum()
   * @generated
   */
  void setIsEnum(boolean value);

  /**
   * Returns the value of the '<em><b>Automated Expansion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Automated Expansion</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Automated Expansion</em>' attribute.
   * @see #setAutomatedExpansion(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_AutomatedExpansion()
   * @model
   * @generated
   */
  boolean isAutomatedExpansion();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isAutomatedExpansion <em>Automated Expansion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Automated Expansion</em>' attribute.
   * @see #isAutomatedExpansion()
   * @generated
   */
  void setAutomatedExpansion(boolean value);

  /**
   * Returns the value of the '<em><b>Allow Fuzzy Extraction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Allow Fuzzy Extraction</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Allow Fuzzy Extraction</em>' attribute.
   * @see #setAllowFuzzyExtraction(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getEntityType_AllowFuzzyExtraction()
   * @model
   * @generated
   */
  boolean isAllowFuzzyExtraction();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.EntityType#isAllowFuzzyExtraction <em>Allow Fuzzy Extraction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Allow Fuzzy Extraction</em>' attribute.
   * @see #isAllowFuzzyExtraction()
   * @generated
   */
  void setAllowFuzzyExtraction(boolean value);

} // EntityType
