/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getInputContexts <em>Input Contexts</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getAffectedContexts <em>Affected Contexts</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getFile <em>File</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getTrainingPhrases <em>Training Phrases</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#getResponses <em>Responses</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#isWebHook <em>Web Hook</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.Intent#isWebHookForSlotFilling <em>Web Hook For Slot Filling</em>}</li>
 * </ul>
 *
 * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent()
 * @model
 * @generated
 */
public interface Intent extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getParameters();

  /**
   * Returns the value of the '<em><b>Input Contexts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.InputContext}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Input Contexts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Contexts</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_InputContexts()
   * @model containment="true"
   * @generated
   */
  EList<InputContext> getInputContexts();

  /**
   * Returns the value of the '<em><b>Affected Contexts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.OutputContext}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Affected Contexts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Affected Contexts</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_AffectedContexts()
   * @model containment="true"
   * @generated
   */
  EList<OutputContext> getAffectedContexts();

  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>File</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.Intent#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>Training Phrases</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.TrainingPhrase}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Training Phrases</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Training Phrases</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_TrainingPhrases()
   * @model containment="true"
   * @generated
   */
  EList<TrainingPhrase> getTrainingPhrases();

  /**
   * Returns the value of the '<em><b>Responses</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Responses</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Responses</em>' attribute list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_Responses()
   * @model unique="false"
   * @generated
   */
  EList<String> getResponses();

  /**
   * Returns the value of the '<em><b>Web Hook</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Web Hook</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Web Hook</em>' attribute.
   * @see #setWebHook(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_WebHook()
   * @model
   * @generated
   */
  boolean isWebHook();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.Intent#isWebHook <em>Web Hook</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Web Hook</em>' attribute.
   * @see #isWebHook()
   * @generated
   */
  void setWebHook(boolean value);

  /**
   * Returns the value of the '<em><b>Web Hook For Slot Filling</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Web Hook For Slot Filling</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Web Hook For Slot Filling</em>' attribute.
   * @see #setWebHookForSlotFilling(boolean)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getIntent_WebHookForSlotFilling()
   * @model
   * @generated
   */
  boolean isWebHookForSlotFilling();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.Intent#isWebHookForSlotFilling <em>Web Hook For Slot Filling</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Web Hook For Slot Filling</em>' attribute.
   * @see #isWebHookForSlotFilling()
   * @generated
   */
  void setWebHookForSlotFilling(boolean value);

} // Intent
