/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dialogflowConfig.OutputContext#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.OutputContext#getLifespan <em>Lifespan</em>}</li>
 * </ul>
 *
 * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getOutputContext()
 * @model
 * @generated
 */
public interface OutputContext extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(EntityType)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getOutputContext_Type()
   * @model
   * @generated
   */
  EntityType getType();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.OutputContext#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(EntityType value);

  /**
   * Returns the value of the '<em><b>Lifespan</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lifespan</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lifespan</em>' attribute.
   * @see #setLifespan(int)
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getOutputContext_Lifespan()
   * @model
   * @generated
   */
  int getLifespan();

  /**
   * Sets the value of the '{@link org.xtext.dialogflowConfig.OutputContext#getLifespan <em>Lifespan</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lifespan</em>' attribute.
   * @see #getLifespan()
   * @generated
   */
  void setLifespan(int value);

} // OutputContext
