/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Phrase</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dialogflowConfig.TrainingPhrase#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getTrainingPhrase()
 * @model
 * @generated
 */
public interface TrainingPhrase extends EObject
{
  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.dialogflowConfig.AbstractWord}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference list.
   * @see org.xtext.dialogflowConfig.DialogflowConfigPackage#getTrainingPhrase_Data()
   * @model containment="true"
   * @generated
   */
  EList<AbstractWord> getData();

} // TrainingPhrase
