/**
 * generated by Xtext 2.16.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.DialogflowConfigRuntimeModule;
import org.xtext.DialogflowConfigStandaloneSetup;
import org.xtext.ide.DialogflowConfigIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DialogflowConfigIdeSetup extends DialogflowConfigStandaloneSetup {
  @Override
  public Injector createInjector() {
    DialogflowConfigRuntimeModule _dialogflowConfigRuntimeModule = new DialogflowConfigRuntimeModule();
    DialogflowConfigIdeModule _dialogflowConfigIdeModule = new DialogflowConfigIdeModule();
    return Guice.createInjector(Modules2.mixin(_dialogflowConfigRuntimeModule, _dialogflowConfigIdeModule));
  }
}
