/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dialogflowConfig.AbstractWord;
import org.xtext.dialogflowConfig.DialogflowConfigPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Word</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AbstractWordImpl extends MinimalEObjectImpl.Container implements AbstractWord
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractWordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DialogflowConfigPackage.Literals.ABSTRACT_WORD;
  }

} //AbstractWordImpl
