/**
 * generated by Xtext 2.16.0
 */
package org.xtext.dialogflowConfig.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.dialogflowConfig.DialogflowConfigPackage;
import org.xtext.dialogflowConfig.EntityType;
import org.xtext.dialogflowConfig.OutputContext;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Output Context</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.dialogflowConfig.impl.OutputContextImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.dialogflowConfig.impl.OutputContextImpl#getLifespan <em>Lifespan</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OutputContextImpl extends MinimalEObjectImpl.Container implements OutputContext
{
  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected EntityType type;

  /**
   * The default value of the '{@link #getLifespan() <em>Lifespan</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLifespan()
   * @generated
   * @ordered
   */
  protected static final int LIFESPAN_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getLifespan() <em>Lifespan</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLifespan()
   * @generated
   * @ordered
   */
  protected int lifespan = LIFESPAN_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OutputContextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DialogflowConfigPackage.Literals.OUTPUT_CONTEXT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityType getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (EntityType)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EntityType basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(EntityType newType)
  {
    EntityType oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getLifespan()
  {
    return lifespan;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLifespan(int newLifespan)
  {
    int oldLifespan = lifespan;
    lifespan = newLifespan;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DialogflowConfigPackage.OUTPUT_CONTEXT__LIFESPAN, oldLifespan, lifespan));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case DialogflowConfigPackage.OUTPUT_CONTEXT__LIFESPAN:
        return getLifespan();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE:
        setType((EntityType)newValue);
        return;
      case DialogflowConfigPackage.OUTPUT_CONTEXT__LIFESPAN:
        setLifespan((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE:
        setType((EntityType)null);
        return;
      case DialogflowConfigPackage.OUTPUT_CONTEXT__LIFESPAN:
        setLifespan(LIFESPAN_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DialogflowConfigPackage.OUTPUT_CONTEXT__TYPE:
        return type != null;
      case DialogflowConfigPackage.OUTPUT_CONTEXT__LIFESPAN:
        return lifespan != LIFESPAN_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (lifespan: ");
    result.append(lifespan);
    result.append(')');
    return result.toString();
  }

} //OutputContextImpl
